[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []
cmds = ["corepack enable && corepack prepare pnpm@10.26.2 --activate"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter dapp build"]

[start]
cmd = "cd packages/dapp && pnpm start"
